name: data_class_tools
description: Data Class Tools
version: 0.0.1
author: Lloyd Albin
homepage: https://github.com/LloydAlbin/data_class_tools

environment:
  sdk: '>=2.19.6 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  # https://pub.dev/packages/path_provider
  # path_provider: ^2.0.14 
  # https://stackoverflow.com/questions/74675982/setting-field-value-with-a-setter-with-field-name-value-as-parameter
  # https://pub.dev/packages/reflectable
  # Because json_config_generator <0.1.3 depends on analyzer ^2.4.0 and no versions of json_config_generator match >0.1.3 <0.2.0, json_config_generator <0.1.3-∞ or >0.1.3 <0.2.0 requires analyzer ^2.4.0.
  # And because json_config_generator 0.1.3 depends on analyzer ^3.1.0 and reflectable >=4.0.5 depends on analyzer ^5.4.0, json_config_generator <0.2.0 is incompatible with reflectable >=4.0.5.
  # So, because postgres_conf_lead_manager depends on both reflectable ^4.0.5 and json_config_generator ^0.1.1, version solving failed.
  # 3.0.8 is compatable with json_config_generator
  reflectable: ^4.0.5
  # https://pub.dev/packages/build_modules/install
  # Fixes these errors
  # Try correcting the name to the name of an existing method, or defining a method named 'toJson'.
  #   (m) => Module.fromJson(_deserialize(m)), (m) => _serialize(m.toJson()));
  #                                                                ^^^^^^
  #build_modules: ^4.0.5
  build_modules: ^4.0.7
  # https://pub.dev/packages/uuid_type
  uuid_type: ^2.0.0
  # https://pub.dev/packages/http
  http: ^0.13.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  # https://pub.dev/packages/build_runner
  build_runner: ^2.2.0
  build_web_compilers: 
  # https://pub.dev/packages/json_config_generator
  #json_config_generator: ^0.1.3
  json_config_generator:
    git: https://github.com/LloydAlbin/json_config_generator.git

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # To add assets to your package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
